### ISSUE TITLE
Idea: only automerge non-breaking changes

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaRegistries/RegistryCI.jl#103]
I believe that this was suggested originally by @KristofferC on Slack.

What if we only automerge non-breaking (i.e. backwards compatible) releases?

So, for example, the following releases **would** be automerged:
- `1.4.7` to `1.4.8`
- `1.4.7` to `1.5.0`
- `0.4.7` to `0.4.8`

The following releases would **not** be automerged, and would require manual review:
- `1.4.7` to `2.0.0`
- `0.4.7` to `0.5.0`

This would make people think twice before they released e.g. `0.1.0` to `0.2.0` as a non-breaking feature release.

However, I **would** like to automerge a breaking release if it takes a package from `0.y.z` to `1.0.0`. So, for example, the following releases **would** be automerged:
- `0.4.7` to `1.0.0`
- `0.0.7` to `1.0.0`

This could serve as an incentive for people to release version `1.0.0` of their package.

**Comment by davidanthoff** [comment]
I'm not convinced these kind of incentives work in the real world. Often they backfire. For example, in this case, you are now giving me an incentive to declare a breaking release as non-breaking so that I get a faster merge time.

I would much prefer that if try to merge a breaking change, that the bot went off on its own and tested all the packages that depend on my package, and then opens a PR that adjusts the bounds of those packages that still seem to work with my new breaking version (where apparently it was maybe not breaking for some of my dependencies).

**Comment by DilumAluthge** [comment]
Seems like this is an unpopular idea.
