### ISSUE TITLE
Proposal: Drop the "can’t narrow Julia compat in a patch release" requirement for pre-1.0 packages

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaRegistries/RegistryCI.jl#204]
Currently, we don’t allow you to narrow the Julia compat in a patch release.

However, this means that if your package is pre-1.0, you have to make a breaking release in order to narrow the Julia compat, even if your package does not make any breaking changes.

I’d like to propose that we:
- Drop this requirement for pre-1.0 packages
- Keep this requirement for post-1.0 packages

**Comment by oxinabox** [comment]
Strong agree.

To my mind:
the main reason to disallow it in patch releases is so that one can go back and make more releases to the old version that supported old julia. E.g. bugfixes.

But a package that hasn't release version 1.0 yet probably doesn't really care about backporting bug fixs to users who are stuck on an old version of the package cos they can't upgrade julia.
