### ISSUE TITLE
Package update stuck for hours at JuliaRegistries

### ISSUE THREAD

**Issue by JeffFessler** [JuliaRegistries/RegistryCI.jl#258]
The README at https://github.com/JuliaRegistries/General says that new versions of existing packages should take 15 minutes to update by JuliaRegistrator, but mine has been stuck for many hours:
https://github.com/JuliaRegistries/General/pull/17858
It says to report issues here.

Probably the issue is that initially I accidentally made a PR that skipped from 0.10 to 0.12.  The bot complained of course, so I canceled that PR and then did the 0.11 update which went fine.  Then I made more breaking changes and tried to do the 0.12 update and it says it passed the test (18 hours ago) but it is not proceeding.

BTW, I left a comment (without `[noblock]`) *before* doing the new request.  Maybe that is blocking things?
But that comment applied to the initial request, not to the revised request...

**Comment by ericphanson** [comment]
Yes, I think it's the lack of `[noblock]`. You can just edit that in and it should work, I believe

**Comment by DilumAluthge** [comment]
Yeah just add `[noblock]` to all of your comments.

**Comment by JeffFessler** [comment]
Thanks that did the trick!  Noob error...
Clearly I didn't realize the absence of a `[noblock]` would persist to affect later PRs.

**Comment by ericphanson** [comment]
Yeah, the way it works is that every 15 minutes or so, the automerge checker runs and looks at each open PR and decides whether or not to merge it, and in deciding that, it looks at each comment of the PR and checks for `[noblock]`. So that's both why all comments must have `[noblock]` to work, but also why editing it in later works.

I feel like it's slightly unintuitive at first, but makes sense once you know how it works. Intuitively, it feels like making the comment triggers something and that can block or not block the merge, so it both feels like it shouldn't trigger later iterations of the PR since those don't exist yet when the comment is made, and also feels like editing shouldn't really help since the "blocking action" has already been done. But actually it's way simpler than that, and just checks for those comments each time.
