### ISSUE TITLE
License checks

### ISSUE THREAD

**Issue by aviks** [JuliaRegistries/RegistryCI.jl#261]
We should check the existence of a license file before merging new packages. We should also, ideally, check that the license is a valid open source licence before automerging. 

I noticed that recently a package was added without a license. https://github.com/JuliaRegistries/General/pull/18690

**Comment by aviks** [comment]
Above package still hasnt added a license. I noticed yet another package registered without a licence. Presumably we should remove packages from the registry that do not have a valid OSI license?

**Comment by aviks** [comment]
Package without license: https://github.com/JuliaRegistries/General/pull/20372

**Comment by fredrikekre** [comment]
What tool do JuliaHub use to detect the license?

**Comment by DilumAluthge** [comment]
I can't speak for Juliahub, but if I understand correctly I think github has a API for getting the license of a repository? For auto merge we could try to use that?

**Comment by DilumAluthge** [comment]
https://developer.github.com/v3/licenses/#get-the-license-for-a-repository

**Comment by DilumAluthge** [comment]
> Presumably we should remove packages from the registry that do not have a valid OSI license?

I agree.

**Comment by DilumAluthge** [comment]
> https://developer.github.com/v3/licenses/#get-the-license-for-a-repository

The problem is that this API will only work if the package is hosted on GitHub.

**Comment by fredrikekre** [comment]
Would it be "legally valid" to put something like "If you do not have a license file in the repository you agree to license the code under the MIT license." in the agreements for this registry?

**Comment by aviks** [comment]
> The problem is that this API will only work if the package is hosted on GitHub.

That is more than 99% or packages, I think, so should be OK? I mean, this just for auto-merge, not fully rejecting the merge

> What tool do JuliaHub use to detect the license?

We used to use [licensee](https://github.com/licensee/licensee), which is what github uses, I believe. Not the most accurate, but does the job IMO. 

>Would it be "legally valid" to put something like

I don't think so, if only for the reason that the user of the package cannot be confident of an implicit contract between the registry and the submitter.

**Comment by aviks** [comment]
Another package registered without a license: https://github.com/Neutrino155/PolaronMakie.jl

**Comment by DilumAluthge** [comment]
Yeah AutoMerge really needs a OSI-compatible license requirement.

**Comment by ericphanson** [comment]
There might be some false-positives from things like https://github.com/ericphanson/GuessworkQuantumSideInfo.jl/blob/14d0be24aebb775c6486cc24798945bfbfacb9b8/LICENSE, where I've included the license of another project I borrowed code from. I think that provision of the MIT license is not always followed and we should aim to not punish people for correctly attributing derived code. (Ref https://github.com/licensee/licensee/issues/424 which has some workarounds for licensee).

But I think to start we could at least require a LICENSE file exists for automerging as a start, which would already catch things like PolaranMakie.

In my opinion, I think the General registry should also, separately, have a policy that requires an OSI-approved license, even if that policy is not (or not yet) enforced by automerge. I think that is an expectation some of us have but is not stated anywhere. Then if it's noticed that a package does not meet this requirement (like PolaranMakie), maintainers of the General registry could request that a license be added, or else yank the package. There was a contentious discussion on Slack months ago about this though, so this kind of thing should probably be discussed more thoroughly on discourse or etc before being enacted. [Note that this is semi off-topic here since it's a General issue, not a RegistryCI issue].

**Comment by aviks** [comment]
Yes, I think it would make sense for a check for the existance of LICENSE/LICENSE.md/COPYING prior to automerge be done asap, while we figure out more sophisticated checks. 

Also, there used to be a [clear requirement](https://github.com/julialang/METADATA.jl#historical-readme) for an OSI approved license in METADATA. Did we lose that in the migration to General? I've always expected that this requirement is present.

**Comment by ericphanson** [comment]
Ah good point. I've opened https://github.com/JuliaRegistries/General/issues/24038 to discuss that so that this issue can be dedicated to the automerge feature.

I looked at implementing just an "existence" check last night, but realized we don't have any checks that look at the package repo itself currently, so we would need to clone the package (or maybe use the Github API). I think that can be done by reusing some the tagbot code (https://github.com/JuliaRegistries/RegistryCI.jl/blob/5fa5dda2d4fa22d515be6f8252c0e37d99de4e64/src/TagBot/TagBot.jl#L32-L49); does that sound like the right approach @DilumAluthge ?

I think maybe this check should also be easily made optional since private registries may not want automated license checking.

**Comment by DilumAluthge** [comment]
1. If it is a GitHub package, then use the GitHub License API: https://developer.github.com/v3/licenses/#get-the-license-for-a-repository

2. Else, get the package code by using `Pkg.add` (no need to assume that the package is a Git repo), then look at the package files, look for LICENSE or LICENSE.md, then run the license through https://github.com/licensee/licensee. We'll have to figure out how to run ruby code. We can assume that GitHub Actions will have ruby installed, but we'll still have to install the gems.

**Comment by DilumAluthge** [comment]
> I think maybe this check should also be easily made optional since private registries may not want automated license checking.

Definitely needs to be opt-in only.

**Comment by ericphanson** [comment]
My new wrapper package https://github.com/ericphanson/LicenseCheck.jl might be able to help here; one nice thing about the library `licensecheck` it wraps is that it will try to look for more than 1 license in the file, so for the example of https://github.com/ericphanson/GuessworkQuantumSideInfo.jl/blob/14d0be24aebb775c6486cc24798945bfbfacb9b8/LICENSE it returns

```julia
julia> licensecheck(text)
(licenses = ["MIT", "MIT"], percent_covered = 93.05555555555556)
```

In other words, it detects both licenses in the file and sees they are both MIT licenses. It handles all the SPDX licenses (and returns their "license ID"s), so we can use something like https://github.com/spdx/license-list-data/blob/master/json/licenses.json to assemble a list of OSI-compatible licenses and check the license IDs against those. The `percent_covered` acts as a safety check to see if we have matched most of the text or not; we can have some threshold so that if there is a bunch of text we have not matched, then we can assume we've missed a license and error out.
