### ISSUE TITLE
TODO: Figure out how to automerge JLL packages

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaRegistries/RegistryCI.jl#6]

**Comment by DilumAluthge** [comment]
@staticfloat

**Comment by DilumAluthge** [comment]
@staticfloat So, I think I have an idea for how to automerge JLL packages. It will not require you to make any changes to your PR titles or your workflows in general.

I'll put a prototype together, will keep you posted.

**Comment by staticfloat** [comment]
I'm just about to get to this; (I've been chewing through other things over the past two weeks)

What do you think about this, it would be something much more similar to what Registrator creates:

* All Yggdrasil builds will come in as a PR from a certain user (Perhaps `@jlbuild`, unless someone has a better username for me to use).
* The title will be something like `JLL Registration: $(name) v$(version)`
* The body will be something like:
```
* Registering JLL package $(name)
* Repository: https://github.com/JuliaBinaryWrappers/$(name)_jll
* Version: v$(version)
```

Because we don't have JLL package restrictions on version numbers, it seems like we don't need to worry about new vs. updated packages, so we don't need to worry about different titles or anything like that.

**Comment by DilumAluthge** [comment]
I think that the second line of the body should look like this, right? I.e. there is a `.jl` at the end of the URL?
```
* Repository: https://github.com/JuliaBinaryWrappers/$(name)_jll.jl
```

**Comment by fredrikekre** [comment]
Why not just use registrator instead of reinventing the wheel?

**Comment by staticfloat** [comment]
Internally, much of this is using `Registrator.jl`, but because the rules are different for JLL packages, (strange version numbers, shouldn't need to argue about naming, etc...) I think it makes sense for these to look differently.

**Comment by DilumAluthge** [comment]
@staticfloat pinged me on Slack that everything is set on their end, so we need to implement automerging on our end.

Unfortunately I am swamped right now and won’t have the time to work on this anytime soon. @fredrikekre @staticfloat would either of you have time to add JLL automerging to RegistryCI? Basically need to check if it’s a JLL package, and if so exempt it from the version number and compat bounds requirements.

If not, I’ll try to work on it when I have the time.... realistically speaking, that might not be until next year 😬
